### PR TITLE
Apt files cleanup

### PR DESCRIPTION
**Pull request by pimuzzo**
Fix database ready before start application is needed to run PrestaShop in a docker compose file, to use a separate (and persistent) docker image of MySql.
Ref: https://docs.docker.com/compose/faq/#how-do-i-get-compose-to-wait-for-my-database-to-be-ready-before-starting-my-application

PS: after installed netcat I've removed lists/*
Ref: https://docs.docker.com/engine/articles/dockerfile_best-practices/#apt-get

### CODE REVIEW

**Comment by manuelmazzuola** [comment]
+1

**Comment by Quetzacoalt91** [comment]
Hi @pimuzzo,

I like your suggestion related to the apt files cleanup and I would like to include it in the repository.

However, I would prefer the MySQL health check from the PR #9. The main is that we do not need to install a new package from `apt-get`.

Would up mind update your PR in order to include only the file cleanup ?

Best regards

**Comment by pimuzzo** [comment]
@Quetzacoalt91 I kept only the apt files cleanup :)
Thanks for the opportunity!

**Comment by mickaelandrieu** [comment]
sounds OK to me :) thank you @pimuzzo

**Comment by Quetzacoalt91** [comment]
Awesome @pimuzzo !
Thanks for your help, your PR is now merged :wink: 

Best regards

**Pull request merged**
