### PR TITLE
Set PS_COUNTRY=GB by default

### PR DESCRIPTION
**Pull request by jsshandle**
Running the latest PrestaShop Docker image with option ``PS_INSTALL_AUTO=1`` leads to an error when using the default value ``PS_COUNTRY=gb``. This error does not occur when using the capitalized version ``PS_COUNTRY=GB``. This pull requests adjusts the default value accordingly.

Use the following commands to reproduce the error:
```
$ docker run -ti --name some-mysql -e MYSQL_ROOT_PASSWORD=admin -d mysql
$ docker run -ti --name some-prestashop --link some-mysql -e DB_SERVER=some-mysql -e PS_INSTALL_AUTO=1 -p 8080:80 -d prestashop/prestashop
```

Error message:
```
* Installing PrestaShop, this may take a while ...
Catchable Fatal Error: Argument 1 passed to PrestaShopBundle\Translation\Loader\SqlTranslationLoader::setTheme() must be an instance of PrestaShop\PrestaShop\Core\Addon\Theme\Theme, null given, called in /var/www/html/classes/Context.php on line 376 and defined
* Almost ! Starting Apache now
```

See the following commands for comparison:
```
$ docker run -ti --name some-mysql -e MYSQL_ROOT_PASSWORD=admin -d mysql
$ docker run -ti --name some-prestashop --link some-mysql -e DB_SERVER=some-mysql -e PS_INSTALL_AUTO=1 -e PS_COUNTRY=GB -p 8080:80 -d prestashop/prestashop
```

Log message:
```
* Installing PrestaShop, this may take a while ...
-- Installation successful! --

* Almost ! Starting Apache now
```

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
What? Wait, that was all?

**Comment by Quetzacoalt91** [comment]
No, keep your PR untouched. I want your change to be applied on all base images. :)

**Comment by romeritoCL** [comment]
Same Same here, I faced the issue and setting the country to upper case fixes it. In my case I was having:

`* Installing PrestaShop, this may take a while ...
 PHP Fatal error:  Uncaught exception 'PrestaShopException' with message 'Property Currency->decimals is not valid' in /var/www/html/classes/ObjectModel.php:909`

Hope this gets fixed soon

**Comment by Quetzacoalt91** [comment]
Let me fix the compilation issue with #118, and I'll be back.

**Comment by Quetzacoalt91** [comment]
Thank you @jsshandle

**Pull request merged**
