### PR TITLE
Upgrade memory_limit from 256M to 512M

### PR DESCRIPTION
**Pull request by hugofintecture**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Upgrade memory_limit from 256M to 512M to avoid some "Error: Allowed memory size"
| Type?             | improvement 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Sponsor company   | Fintecture
| How to test?      | Nothing should change

We think it's better for development purposes but maybe your prefer to follow this line from "[The more the merrier. We recommend setting the memory allocation per script (memory_limit) to a minimum of 256M.](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/)"?

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]
Hi @hugofintecture, thanks for your PR!
As we explain here https://devdocs.prestashop-project.org/8/basics/installation/environments/docker/:
> PrestaShop is available through Docker for testing/experimenting and developing modules or themes.

So for me, its ok to switch to 512M in docker image and leave the line that you mention in your PR description as is.
But maybe, it can be usefull to have a third approval on this one, just to be sure!

**Comment by kpodemski** [comment]
@jolelievre publish action doesn't work because of the login/password, I think you have worked on this thing?

**Comment by jolelievre** [comment]
@kpodemski yes it's because the secrets are set on the Organisation level and can only be accessed for PRs belonging to the repository only It doesn't work for a PR which source branch comes from a fork But it should work once it's merged on master

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
> 
@kpodemski yes it's because the secrets are set on the Organisation level and can only be accessed for PRs belonging to the repository only It doesn't work for a PR which source branch comes from a fork But it should work once it's merged on master

Then we should modify the GH Action to only run after a merge in the branch, not for pull requests

**Pull request merged**
