### PR TITLE
Uprev actions/checkout to v3

### PR DESCRIPTION
**Pull request by Sushrut1101**
For hacktoberfest 2022 :)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
CI build "Run Flake8 with python 3.7" fails. I ran it twice. Running a 3rd time 🤔

**Comment by matks** [comment]
This build continues to be red https://github.com/PrestaShop/docker/actions/runs/3169414350/jobs/5162187982

**Comment by Sushrut1101** [comment]
> This build continues to be red https://github.com/PrestaShop/docker/actions/runs/3169414350/jobs/5162187982

The red job has actions/checkout@v2 😬

**Comment by matks** [comment]
Closing and re-opening to see if I can reset this PR state

**Comment by matks** [comment]
@Sushrut1101 I'm really sorry but I have no idea why CI is failing 😭

**Comment by matks** [comment]
I close this PR as stale unfortunately 😢

**Pull request closed without merging**
