### PR TITLE
Add PHP 8.3 in the base docker images

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add PHP 8.3 in the base docker images so that they can be used for UI tests and sanity tests<br>To generate the base images we updated the `tags.txt` file and then we ran the `base/generate_tags.sh -f` (-f important o update all the bases) script so that it generates the base files based on the model<br>The we added the 8.3 version for nightly only (version 9.0 under development) and used the `./prestashop_docker.py generate` script to generate its docker files
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Sponsor company   | ~
| How to test?      | ~

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
seems like there's a problem logging with docker hub, it's expecting a nickname and password

**Review by tleon — APPROVED** [review]
Aren't the problems on the CI because this is on a fork ?

**Comment by jolelievre** [comment]
@tleon yes they are, the publication cannot work on my fork because I don't have the secrets defined to push, we should probably change the workflows a bit so that they only run on merged PR it's not very useful o run this on each PR it could even be dangerous as it could push some non validated PR towards Docker

But the addition of 8.3 version is temporarily paused We have some bugs in the BO that are cause by Symfony, it's more efficient to wait for a few weeks for them to fix them, especially since we're gonna upgrade to SF6 that also should include some improvements for recent versions of PHP

**Review by Quetzacoalt91 — APPROVED** [review]
I was looking to add PHP 8.3 today, but it appears you bring the same changes here

**Pull request merged**
