### PR TITLE
Create database if not exists

### PR DESCRIPTION
**Pull request by Whazor**
Needed for automatically installing PrestaShop

### CODE REVIEW

**Comment by Whazor** [comment]
i didnt see the commands above, but i'm still wondering why my environment would not run...

**Comment by Quetzacoalt91** [comment]
Hi @Whazor,

I guess something went wrong during the database creation with `mysqladmin`, but nothing appeared because of the error output redirected.
I will check on my side if I can display the potential errors. Meanwhile, if you do not use the internal database, you should verify if your have the good credentials and if you have the needed permissions granted. 

Best regards

**Comment by Whazor** [comment]
My problem is that I am using docker-machine and I have to change the domain because the ip is different. Now I have the environment working.

Another change I had to make is, after --language... should be a space before the \

**Comment by Quetzacoalt91** [comment]
About the domain, it is automatically updated with the IP you actually use when you try to reach the front-office for the first time.

See the file https://github.com/PrestaShop/docker/blob/b24a9e30688ce16c0b577f2868b7f66704136900/config_files/docker_updt_ps_domains.php

**Pull request closed without merging**
