### PR TITLE
Release 1761

### PR DESCRIPTION
**Pull request by matks**
- Add v1.7.6.1 to the managed versions list
- Regenerate docker images to use the v1.7.6.1 from prestashop.com

### CODE REVIEW

**Comment by matks** [comment]
Should fix https://github.com/PrestaShop/docker/pull/175

**Comment by PierreRambaud** [comment]
`Package mysql-client is not available, but is referred to by another package`

Look like containers need to be updated :/

**Comment by Quetzacoalt91** [comment]
Can you please rebase?

**Comment by Quetzacoalt91** [comment]
Thank you @matks

**Pull request merged**
