### PR TITLE
Updated the domain update script to update data depending on domain

### PR DESCRIPTION
**Pull request by Clovel**
Signed-off-by: Clovis Durand <cd.clovel19@gmail.com>

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Resources like images were not updated when the dynamic host was changed. 
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | Deploy PrestaShop using a docker image on a server, behind an NGINX or Apache reverse proxy. Set a DNS record with a subdomain name to point to this server. Change said record to another subdomain. Check if everything is in place
| Possible impacts? | None detected so far.

This was tested by inserting the 4 new lines of code in a running instance of PrestaShop in a Docker container. 2 images were used in the test : 
- `bitnami/mariadb:latest`
- `prestashop/prestashop:latest`

Test was conducted in late July of 2022.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Woah 😅 I did not know this file existed. I have no idea how it's supposed to be used.

@Quetzacoalt91 you modified this file many years ago can you explain `docker_updt_ps_domain.php` is used? When is it loaded/run ?

**Comment by Quetzacoalt91** [comment]
Hello,

That's a toggle we implemented in the first version of the Docker images, because as you know PrestaShop redirects the user when the URL stored in the database does not match.
At each restart the IP changes, so it was easier to use this toggle to keep the shop accessible.

**Comment by Clovel** [comment]
> This file is supposed to be called at the container startup.

We have a use case when on DNS domain change, we automatically restart the container after backing it up in a private docker registry. Thus the need to regenerate lots of things, such as the cache or the htaccess. 

Also, as per our testing, we don't need to restart the container for this code to be executed. 

These lines basically come from the back-office domain change feature.

**Review by matks — APPROVED** [review]
I think it makes sense. An opinion @atomiix ?

**Review by atomiix — APPROVED** [review]
@matks I didn't know this file existed either 😄 But yeah, it makes sense to me

**Comment by Clovel** [comment]
Any news on this ?

**Pull request merged**
