### PR TITLE
Build multiarch images (amd64, arm64)

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This PR aims to use buildx builder in order to create multi-arch images of PrestaShop. As Docker doesn't support local multiarch image, the 2 steps (build then push) should be done in one step that exports the images directly to the registry.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | CI should be green
| Possible impacts? |

### CODE REVIEW

**Comment by matks** [comment]
Hohoho @atomiix I was not expecting this, cool 😄  !

Note: this issue might be helpful for https://github.com/PrestaShop/docker/issues/273

**Review by matthieu-rolland — COMMENTED** [review]
We usually close PRs after long inactivities but I'm not sure if you're planning to finish or not @atomiix  ?

**Comment by atomiix** [comment]
That's something I want to finish yes, but I don't know when 😅

**Comment by matks** [comment]
> That's something I want to finish yes, but I don't know when 😅

Is it still your plan 😆 ?

**Comment by atomiix** [comment]
It would be great 😄 But if someone is willing to take the subject, go ahead!

**Comment by matks** [comment]
Hi everyone I believe this PR is now too stale. I close it for now, just to help navigating old PRs. But we can reopen it anytime you want 😉 obviously. A closed PR does not mean it has to stay closed forever 💪 ! I just do this to make it easier to distinguish old PRs that might be merged one day and PRs that - unfortunately - I think are too old and will never be merged.

Thank you anyway for submitting the PR 👍

**Pull request closed without merging**
