### PR TITLE
Add php7.3 for nightly and 1.7

### PR DESCRIPTION
**Pull request by PierreRambaud**

### CODE REVIEW

**Comment by Progi1984** [comment]
@PierreRambaud I fixed that : https://travis-ci.org/PrestaShop/docker/jobs/640822949 here : https://github.com/PrestaShop/docker/pull/200/files#diff-c342d3fa00d39a6a7a0357f9bc43f078

**Comment by PierreRambaud** [comment]
@Progi1984 We need to improve our generated files, because it changes automatically :thinking:

**Comment by Progi1984** [comment]
@PierreRambaud I valid this one and we make it in an another PR ?

**Comment by PierreRambaud** [comment]
Not sure since something is broken :sob:

**Comment by Progi1984** [comment]
@PierreRambaud So We do the reverse.

**Comment by PierreRambaud** [comment]
@Progi1984 No, we need to improve scripts to split old and new php releases

**Comment by Quetzacoalt91** [comment]
Hi @PierreRambaud,

By any chance, do you have some time to make the tests pass so we may have PHP 7.3 available with PrestaShop 1.7.7 during our tests?

**Comment by matks** [comment]
Error with 1.7.6.3 for Apache
```
The command '/bin/sh -c apt-get update 	&& apt-get install -y libmcrypt-dev 		libjpeg62-turbo-dev 		libpcre3-dev 		libpng-dev 		libfreetype6-dev 		libxml2-dev 		libicu-dev 		libzip-dev 		default-mysql-client 		wget 		unzip     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install iconv intl pdo_mysql mbstring soap gd zip' returned a non-zero code: 1

The command "docker build -t "prestashop/base:$BASE" base/images/$BASE" exited with 1.
0.06s$ docker tag prestashop/base:$BASE prestashop/base:5.6-apache
Error response from daemon: No such image: prestashop/base:apache

The command "docker tag prestashop/base:$BASE prestashop/base:5.6-apache" exited with 1.
59.43s$ docker build -t "$image" images/$VERSION
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM prestashop/base:5.6-apache
5.6-apache: Pulling from prestashop/base
```

**Comment by Quetzacoalt91** [comment]
Thank you @PierreRambaud

**Pull request merged**
